name: 反馈 Bug [CN]
description: 反馈错误或异常行为
labels: [bug]
title: "[Bug] (在这里简短描述你发现的问题)"
body:
  - type: markdown
    attributes:
      value: |
        感谢汇报问题！
        这里所有的文本都是英文和中文对照。如果你其中一种语言不懂，没关系。
        带有 \* 的为必填项，请务必填写完整。其他项目如果不了解或不适用，可以留空。
        # 检查清单
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      description: 请确认自己完成了要求之后再进行勾选。我理解如果不满足要求，Issue 可能会被无条件关闭并锁定。
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
          required: true
        - label: 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
          required: true
        - label: 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
          required: true
        - label: 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及
          required: true
        - label: 我正在使用内测版本/公测版本/预发布版本
  - type: input
    attributes:
      label: 任何其他环境信息
      placeholder:
  - type: markdown
    attributes:
      value: ## 这是一些设备信息问题，用于确定您的运行环境。
  - type: input
    attributes:
      label: 操作系统版本
      placeholder:
    validations:
      required: true
  - type: input
    attributes:
      label: 软件版本
      placeholder:
    validations:
      required: true
  - type: input
    attributes:
      label: 环境
      placeholder:
  - type: checkboxes
    id: Internet
    attributes:
      label: 网络
      options:
        - label: 我已检查了网络连接，确认网络正常
          required: true
        - label: 我使用了代理/VPN
        - label: 我位于网络受限的环境。即使已经使用了代理/VPN，也请勾选此项。中国大陆请始终勾选此项。
  - type: markdown
    attributes:
      value: ## 这些是必要问题，请尽可能填写信息。
  - type: textarea
    attributes:
      label: 重现步骤
      placeholder: 描述重现 Bug 的步骤，包括任何必要的设置以重现问题。请提供明确的重现此 Bug 的步骤。如果相关，请包含重现代码。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期行为
      placeholder: 正常情况下应该发生什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际行为
      placeholder: 实际上发生了什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 错误信息
      placeholder: 如果有，请粘贴完整的错误信息
  - type: textarea
    attributes:
      label: 截图
      placeholder: 如果有，请添加截图以帮助解释你的问题
  - type: textarea
    attributes:
      label: 日志
      placeholder: 如果有，请添加日志以帮助解释你的问题
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗?
      placeholder: 任何能让我们对你所遇到的问题有更多了解的东西