blank_issues_enabled: false
contact_links:
  - name: Ask GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: A good place to ask questions and find answers.
  - name: View My Blog (Chinese) it may help you
    url: https://blog.wuyilingwei.com
    about: Some projects I will write in my blog.